# Generated by Django 6.0.3 on 2026-03-17 13:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioFixoDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('horario', models.TimeField()),
                ('ativo', models.BooleanField(default=True, help_text='Define se este horário da grade semanal está ativo')),
            ],
            options={
                'verbose_name': 'Horário Fixo da Semana',
                'verbose_name_plural': 'Grade de Horários Fixos',
                'ordering': ['dia_semana', 'horario'],
                'unique_together': {('dia_semana', 'horario')},
            },
        ),
        migrations.CreateModel(
            name='Medica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm', models.CharField(max_length=20)),
                ('especialidade', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nome_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('crm', models.CharField(blank=True, max_length=20, null=True)),
                ('cargo', models.CharField(max_length=100)),
                ('instituicao', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_res', models.DateTimeField(auto_now_add=True)),
                ('medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teleconsultoria.medica')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='respostas_anexos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='teleconsultoria.resposta')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ANALISE', 'Em Análise'), ('AGENDADO', 'Reunião Agendada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada'), ('AUSENTE', 'Ausente')], default='PENDENTE', max_length=20)),
                ('tipo_atendimento', models.CharField(choices=[('SINCRONO', 'Síncrono'), ('ASSINCRONO', 'Assíncrono')], max_length=20)),
                ('data_sol', models.DateTimeField(auto_now_add=True)),
                ('data_marcada', models.DateField(blank=True, null=True)),
                ('horario_marcado', models.TimeField(blank=True, null=True)),
                ('duracao_estimada', models.PositiveIntegerField(blank=True, help_text='Duração em minutos', null=True)),
                ('link_teams', models.URLField(blank=True, max_length=500, null=True)),
                ('resumo_sincrono', models.TextField(blank=True, null=True)),
                ('justificativa_cancelamento', models.TextField(blank=True, null=True)),
                ('data_limite', models.DateField(blank=True, null=True)),
                ('horario_limite', models.TimeField(blank=True, null=True)),
                ('idade_pac', models.IntegerField()),
                ('sexo_pac', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('queixas', models.TextField()),
                ('historico_med', models.TextField(blank=True, null=True)),
                ('diagnostico_princ', models.TextField(blank=True, null=True)),
                ('diagnostico_sec', models.TextField(blank=True, null=True)),
                ('medicamentos', models.TextField(blank=True, null=True)),
                ('exames_recentes', models.TextField(blank=True, null=True)),
                ('duvida_clinica', models.TextField()),
                ('token_acesso', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('medica_designada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='teleconsultoria.medica')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='teleconsultoria.profissional')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
            },
        ),
        migrations.AddField(
            model_name='resposta',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='teleconsultoria.solicitacao'),
        ),
        migrations.CreateModel(
            name='LinkAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('expirado', models.BooleanField(default=False)),
                ('solicitacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link_magico', to='teleconsultoria.solicitacao')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='solicitacoes_anexos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='teleconsultoria.solicitacao')),
            ],
        ),
    ]
