# Generated by Django 6.0.2 on 2026-02-05 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm', models.CharField(max_length=20)),
                ('especialidade', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=100)),
                ('instituicao', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ANALISE', 'Em Análise'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('tipo_atendimento', models.CharField(choices=[('SINCRONO', 'Síncrono'), ('ASSINCRONO', 'Assíncrono')], max_length=20)),
                ('data_sol', models.DateTimeField(auto_now_add=True)),
                ('data_marcada', models.DateField(blank=True, null=True)),
                ('horario_marcado', models.TimeField(blank=True, null=True)),
                ('data_limite', models.DateField(blank=True, null=True)),
                ('horario_limite', models.TimeField(blank=True, null=True)),
                ('idade_pac', models.IntegerField()),
                ('sexo_pac', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('queixas', models.TextField()),
                ('historico_med', models.TextField(blank=True, null=True)),
                ('diagnostico_princ', models.TextField(blank=True, null=True)),
                ('diagnostico_sec', models.TextField(blank=True, null=True)),
                ('medicamentos', models.TextField(blank=True, null=True)),
                ('exames_recentes', models.TextField(blank=True, null=True)),
                ('duvida_clinica', models.TextField()),
                ('medica_designada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='teleconsultoria.medica')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='teleconsultoria.profissional')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('anexo', models.FileField(blank=True, null=True, upload_to='respostas_anexos/')),
                ('data_res', models.DateTimeField(auto_now_add=True)),
                ('medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teleconsultoria.medica')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='teleconsultoria.solicitacao')),
            ],
        ),
    ]
