# Generated by Django 6.0.3 on 2026-03-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsultoria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='telefone',
        ),
    ]
