# Generated by Django 6.0.2 on 2026-02-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsultoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='solicitacoes_anexos/'),
        ),
    ]
