# Generated by Django 6.0.2 on 2026-02-10 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsultoria', '0002_solicitacao_anexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='anexo',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='anexo',
        ),
        migrations.CreateModel(
            name='AnexoResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='respostas_anexos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='teleconsultoria.resposta')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='solicitacoes_anexos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='teleconsultoria.solicitacao')),
            ],
        ),
    ]
