# Generated by Django 6.0.4 on 2026-04-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsultoria', '0002_remove_profissional_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='telefone',
            field=models.CharField(blank=True, help_text='WhatsApp com DDD', max_length=15, null=True),
        ),
    ]
