# Generated by Django 6.0.2 on 2026-02-12 11:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsultoria', '0003_remove_resposta_anexo_remove_solicitacao_anexo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('expirado', models.BooleanField(default=False)),
                ('solicitacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link_magico', to='teleconsultoria.solicitacao')),
            ],
        ),
    ]
