# Generated by Django 6.0.4 on 2026-05-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsultoria', '0003_profissional_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='sexo_biologico_pac',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='idade_pac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='queixas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='sexo_pac',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=2, null=True),
        ),
    ]
