# Generated by Django 6.0.4 on 2026-06-01 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsultoria', '0004_solicitacao_sexo_biologico_pac_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='resumo_sincrono',
        ),
    ]
