# Generated by Django 6.0.2 on 2026-02-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsultoria', '0004_linkacesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='duracao_estimada',
            field=models.PositiveIntegerField(default=30, help_text='Duração em minutos'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='link_teams',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='resumo_sincrono',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ANALISE', 'Em Análise'), ('AGENDADO', 'Reunião Agendada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20),
        ),
    ]
