# Generated by Django 6.0.2 on 2026-02-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsultoria', '0005_solicitacao_duracao_estimada_solicitacao_link_teams_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadeAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('ativo', models.BooleanField(default=True, help_text='Define se este horário aparece para o solicitante')),
            ],
            options={
                'verbose_name': 'Disponibilidade de Agenda',
                'verbose_name_plural': 'Disponibilidades de Agenda',
                'ordering': ['data', 'horario'],
            },
        ),
    ]
