# Generated by Django 6.0.4 on 2026-06-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsultoria', '0006_alter_medica_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='medica',
            name='nome_completo',
            field=models.CharField(default='Médica Teleconsultora', max_length=255),
        ),
    ]
