# Generated by Django 6.0.2 on 2026-02-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsultoria', '0006_disponibilidadeagenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioFixoDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('horario', models.TimeField()),
                ('ativo', models.BooleanField(default=True, help_text='Define se este horário da grade semanal está ativo')),
            ],
            options={
                'verbose_name': 'Horário Fixo da Semana',
                'verbose_name_plural': 'Grade de Horários Fixos',
                'ordering': ['dia_semana', 'horario'],
                'unique_together': {('dia_semana', 'horario')},
            },
        ),
        migrations.DeleteModel(
            name='DisponibilidadeAgenda',
        ),
    ]
