# Generated by Django 6.0.4 on 2026-06-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsultoria', '0007_medica_nome_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='cpf',
            field=models.CharField(help_text='CPF com ou sem formatação', max_length=14, unique=True),
        ),
    ]
