# Generated by Django 6.0.2 on 2026-02-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsultoria', '0007_horariofixodisponivel_delete_disponibilidadeagenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='justificativa_cancelamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ANALISE', 'Em Análise'), ('AGENDADO', 'Reunião Agendada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada'), ('AUSENTE', 'Não Compareceu')], default='PENDENTE', max_length=20),
        ),
    ]
