# Generated by Django 6.0.4 on 2026-07-01 11:34

import teleconsultoria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsultoria', '0008_alter_profissional_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='token_acesso',
        ),
        migrations.AlterField(
            model_name='anexoresposta',
            name='arquivo',
            field=models.FileField(upload_to='respostas_anexos/', validators=[teleconsultoria.models.validar_arquivo]),
        ),
        migrations.AlterField(
            model_name='anexosolicitacao',
            name='arquivo',
            field=models.FileField(upload_to='solicitacoes_anexos/', validators=[teleconsultoria.models.validar_arquivo]),
        ),
    ]
