# Generated by Django 6.0.2 on 2026-03-05 11:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsultoria', '0008_solicitacao_justificativa_cancelamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='token_acesso',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='duracao_estimada',
            field=models.PositiveIntegerField(blank=True, help_text='Duração em minutos', null=True),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ANALISE', 'Em Análise'), ('AGENDADO', 'Reunião Agendada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada'), ('AUSENTE', 'Ausente')], default='PENDENTE', max_length=20),
        ),
    ]
